fiscaliza-api:
    image: hitalos/laravel:latest
    container_name: fiscaliza-api
    ports:
        - 86:80
    volumes:
        - ./api:/var/www
    links:
        - mongo
    command:
        - /bin/bash
        - -c
        - |
          composer install
          composer require jenssegers/mongodb
          php artisan migrate
          php artisan inicializar:banco
          php artisan serve --port=80 --host=0.0.0.0
mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
        - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

mongo-express:
    image: mongo-express
    container_name: fiscaliza-mongo-gerencial
    restart: always
    ports:
        - 8089:8081
    links:
        - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root

fiscaliza-front:
    image: node:10
    container_name: fiscaliza-front
    ports:
        - 9001:8080
    volumes:
        - ./front:/var/www
    command:
        - /bin/bash
        - -c
        - |
          cd var/www/
          npm i
          npm run serve